import {StyleSheet, Dimensions} from 'react-native'

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'white',
        marginTop:-5,   
    },
    header:{
        height:45,
        backgroundColor:'#71C9DB',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    backIconImageContainer:{
        flex:2,
        alignItems:'center',
        justifyContent:'center',
        position:'absolute',
        alignSelf:'flex-start',
        left:5,
        height:'100%',
        width:50
    },
    drawerIconImage:{
        height:30,
        width:35,
    },
    headerLogoImage:{
        width:123,
        height:32.5,
        bottom:2,
    },
    buttonContainer:{
        height:70,
        borderBottomWidth:2,
        borderColor:'rgba(128,128,128,0.5)',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'white',
    },
    button:{
        height:50,
        width:'40%',
        margin:15,
        borderRadius:5,
        borderWidth:1.5,
        alignItems:'center',
        justifyContent:'center',
    },
    buttonText:{
        fontSize:16,
        fontWeight:'bold',
    },
    bottomNavBar:{
        height:55,
        width:'100%',
        position:'absolute',
        bottom:28,
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
        borderTopColor:'rgba(128,128,128,0.5)',
        borderTopWidth:1,
        paddingTop:5,
        backgroundColor:'white',
    },
    navItem:{
        height:45, 
        width:70,  
        alignItems:'center',
        justifyContent:'center',
    },
    navImage:{
        height:25,
        width:25,
    },
    navText:{
        color:'gray',
        fontSize:12,
    },
    coverImage:{
        height:120,
        resizeMode:'stretch',
        width:Math.round(Dimensions.get('window').width),
        marginTop:2,
    },
    productRowContainer:{
        height:130,
        margin:5,
        flexDirection:'row',
        justifyContent:'space-around'
    },
    scroller:{
        marginBottom:55 + 28,
    },
    product:{
        width:'30%',
        margin:5,
        borderRadius:5,
        borderWidth:2,
        borderColor:'rgba(128,128,128,0.5)',   
    }
})